### ISSUE TITLE
Would love a CSV export feature.

### ISSUE THREAD

**Issue by tamccall** [BellwoodStudios/maker-business-analytics-website#6]
First off great site. I love that we have a way to view historical values for all of these system parameters. Great work!

One feature request i would like to add is that I think it would be great if we could export the data displayed in the graphs to CSV in order to facilitate doing quick calculations on these variables.

Some calculations that I could foresee being useful that a CSV export might help with would be:

- What is the average SF for ETH vaults over the course of the past quarter?
- What is the variance of the ETH SF over the past quarter?
- What is the average DSR rate over the past quarter?
- etc

Just an idea but I personally would find it useful.

**Comment by hexonaut** [comment]
Great idea. A CSV export of the data on the chart is pretty straight forward to add. I'll look at getting that in.
